services:
  - type: web
    name: be-todo
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://todo_user:swAGDfyqLZuwSEHlVG97NIfpW9IFtlhm@dpg-d701e6ndiees73dc9aug-a/todo_app_604x
      - key: DB_SSL
        value: "true"
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    env: docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://be-todo.onrender.com
      - key: NODE_ENV
        value: production
